name: Bump Patch Version

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  setup-telegram-bot:
    name: Bump Patch Version
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run script file
      run: |
         chmod +x ./scripts/bump_version.sh
         ./scripts/bump_version.sh
      shell: bash

    - name: Create a branch
      run: |
        git config --global user.name "capymind_bot"
        git config --global user.email "capymind@github.com"
        git checkout -b bump-patch-version
        git add .
        git commit -m "Bump patch version"
        git push origin bump-patch-version
      shell: bash

    - name: Create a pull request
      uses: peter-evans/create-pull-request@v3
      with:
        branch: 'bump-patch-version'
        delete-branch: true
        commit-message: 'Bump patch version'
        title: 'Bump patch version'
        token: ${{ secrets.GITHUB_TOKEN }}