name: Bump Minor Version
description: This workflow bumps the minor version of the project ex. 1.0.0 -> 1.1.0

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  setup-telegram-bot:
    name: Bump Minor Version
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run script file
      run: |
         chmod +x ./scripts/get_version.sh
         chmod +x ./scripts/bump_version.sh
         ./scripts/bump_version.sh --minor
      shell: bash

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        branch: 'bump-minor-version'
        delete-branch: true
        commit-message: 'Bump minor version'
        title: 'Bump minor version'
        token: ${{ secrets.GITHUB_TOKEN }}