name: Bump Patch Version
description: This workflow bumps the patch version of the project ex. 1.0.0 -> 1.0.1

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  setup-telegram-bot:
    name: Bump Patch Version
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run script file
      run: |
         chmod +x ./scripts/get_version.sh
         chmod +x ./scripts/bump_version.sh
         ./scripts/bump_version.sh
      shell: bash

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        branch: 'bump-patch-version'
        delete-branch: true
        commit-message: 'Bump patch version'
        title: 'Bump patch version'
        token: ${{ secrets.GITHUB_TOKEN }}