name: Deploy Container

on:
  workflow_dispatch:

jobs:
  setup-telegram-bot:
    name: Deploy Google Cloud Container
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - uses: 'google-github-actions/auth@v2.1.4'
      with:
        project_id: ${{ secrets.CAPY_PROJECT_ID }}
        workload_identity_provider: ${{ secrets.CAPY_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.CAPY_SERVICE_ACCOUNT }}

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloudrun@v2'
      with:
        service: 'capymind'
        image: 'gcr.io/cloudrun/capymind'