name: Setup Telegram Bot

 on:
  workflow_dispatch:

 jobs:
   setup-telegram-bot:
     runs-on: ubuntu-latest

     steps:
     - name: Checkout repository
       uses: actions/checkout@v4

    - name: 'Setup Telegram Bot'
      uses: './scripts/setup_telegram_bot.sh'
      env:
        CAPY_TELEGRAM_BOT_TOKEN: ${{ secrets.CAPY_TELEGRAM_BOT_TOKEN }}
        CAPY_CLOUD_FUNCTION_URL: ${{ env.CAPY_CLOUD_FUNCTION_URL }}