name: Deploy Function

on:
  workflow_dispatch:

  jobs:
    deploy:
      runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Setup Telegram Bot'
        uses: './scripts/setup_telegram_bot.sh'
        with:
          CAPY_TELEGRAM_BOT_TOKEN: ${{ secrets.CAPY_TELEGRAM_BOT_TOKEN }}
          CAPY_CLOUD_FUNCTION_URL: ${{ env.CAPY_CLOUD_FUNCTION_URL }}
          