name: Setup Telegram Bot

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  setup-telegram-bot:
    name: Setup Telegram Bot
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up environment variables
      run: echo "CAPY_TELEGRAM_BOT_TOKEN=${{ secrets.CAPY_TELEGRAM_BOT_TOKEN }}" >> $GITHUB_ENV
      run: echo "CAPY_CLOUD_FUNCTION_URL=${{ env.CAPY_CLOUD_FUNCTION_URL }}" >> $GITHUB_ENV

    - name: Run script file
      run: |
         chmod +x ./scripts/setup_telegram_bot.sh
         ./scripts/setup_telegram_bot.sh
      shell: bash