name: Setup Telegram Bot

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  setup-telegram-bot:
    name: Setup Telegram Bot
    runs-on: ubuntu-latest

    env:
      CAPY_TELEGRAM_BOT_TOKEN: ${{ secrets.CAPY_TELEGRAM_BOT_TOKEN }}
      CAPY_CLOUD_FUNCTION_URL: ${{ env.CAPY_CLOUD_FUNCTION_URL }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run script file
      run: |
         chmod +x ./scripts/setup_telegram_bot.sh
         ./scripts/setup_telegram_bot.sh
      shell: bash